pipelines:
  build-publish-jdk8-gradle-fortify-sca-image:
    group: java-gradle-group
    materials:
      mygit:
        branch: master
        git: https://github.com/amrityam/Fortify_SCA_Docker_Images.git
        whitelist:
          - fortify_sca_jdk8_gradle/**/*.*
    stages:
       - publish-image:
          clean_workspace: true
          jobs:
            run:
              tasks:
                - exec:
                   command: bash
                   arguments:
                    - -c
                    - cp -r /var/lib/go-agent/pipelines/fortify-19.1.0 ./Fortify/
                - exec:
                   command: bash
                   arguments:
                    - -c
                    - docker build --no-cache --rm -t https://hub.docker.com/r/amrityam/fortify-sca-images/fortify_sca_jdk8_gradle --file=fortify_sca_jdk8_gradle/Dockerfile .
                - exec:
                   command: bash
                   arguments:
                    - -c
                    - docker push https://hub.docker.com/r/amrityam/fortify-sca-images/fortify_sca_jdk8_gradle
                - exec:
                   command: bash
                   arguments:
                    - -c
                    - docker rmi -f https://hub.docker.com/r/amrityam/fortify-sca-images/fortify_sca_jdk8_gradle
#This pipeline below is to be used by any product on jdk8 and gradle, Just need to change the git repo and arguments in docker run command below
#Rest everything is blackbox for the user.
  Java-Project-Template-fortify-scanning:
    group: java-gradle-group
    materials:
      mygit:
        branch: master
        git: https://github.com/amrityam/Java-Project-Template.git
        destination: source_code
      dev:
        pipeline: build-publish-jdk8-gradle-fortify-sca-image
        stage: publish-image
    stages:
      - staticCode-analysis:
          clean_workspace: true
          jobs:
            run:
              tasks:
                - exec:
                    arguments:
                      - -c
                      - docker run -u `id -u` --rm -v $PWD/source_code:/source_code -e "prod_name=Java-Project-Template" -e "blackduck_hub_project_name=Java-Project-Template" -e "blackduck_hub_project_version=1.0" -e "sonar_fortify_ssc_appversion=Java-Project-Template:1.0" -e "sonar_projectKey=Java-Project-Template" -e "sonarExtParam=" https://hub.docker.com/r/amrityam/fortify-sca-images/fortify_sca_jdk8_gradle
                    command: bash
                - exec:
                    arguments:
                      - -c
                      - rm -rf .gradle/
                    command: bash    
